[api]
  enabled = true
  address = "[::]:8686"

[sources.fly_log_metrics]
  type = "internal_metrics"

[sources.nats]
  type = "nats"
  url = "nats://[${NETWORK-fdaa}::3]:4223"
  queue = "${QUEUE-}"
  subject = "${SUBJECT-logs.>}"
  auth.strategy = "user_password"
  auth.user_password.user = "${ORG-personal}"
  auth.user_password.password = "${ACCESS_TOKEN?}"
  connection_name = "Fly logs stream"

[transforms.log_json_from_fly]
  type = "remap"
  inputs = ["nats"]
  source = '''
  . = parse_json!(.message)
  '''

[transforms.log_json]
type = "remap"
inputs = ["log_json_from_fly"]
source = '''
if exists(.message) && is_string(.message) {
  # Detect JSON-encoded structured log data based on first occurence of opening curly brace '{'
  # either as the first character or preceded by whitespace (ignoring any ANSI SGR escape codes)
  # Handles both a real ESC char (\x1b) and literal "\u001b" sequences.
  parsed = parse_regex(
    .message,
    r'^(?P<message_text>.*?)(^|(?P<sep>\s+))(?:(?:\x1b|\\u001b)\[[0-9;]*m)*\s*(?P<metadata>\{.*\})(?:\s*(?:(?:\x1b|\\u001b)\[[0-9;]*m)*)\s*$'
  ) ?? null

  if parsed != null {
    prefix = to_string(parsed.message_text)
    sep = to_string(parsed.sep)
    # require whitespace separator before opening json bracket
    # unless we have no message prefix before the json
    if sep == "" && prefix != "" {
      parsed = null
    }
  }

  if parsed != null {
    metadata = parse_json(parsed.metadata) ?? null

    if is_object(metadata) && is_object(.) {
      message_text = replace(to_string(parsed.message_text), r'\s+$', "")

      # Only keep trimmed prefix as .message if there actually is one
      if message_text != "" {
        .message = message_text
      } else {
        del(.message)
      }

      . = merge!(., metadata, deep: true)
    }
  }
}

org = get_env_var("ORG") ?? null
if org != null && is_object(.fly) {
  .fly.org = org
}
'''

[sinks.fly_log_metrics_prometheus]
  type = "prometheus_exporter" # required
  inputs = ["fly_log_metrics"] # required
  address = "[::]:9598" # required
  default_namespace = "fly-logs" # optional, no default

[sinks.blackhole]
  type = "blackhole"
  inputs = ["log_json"]
  print_interval_secs = 100000
